### PR TITLE
Ignore enum member's type & type argument with specific enum

### PR DESCRIPTION
**Pull request by N0I0C0K**
In some type checkers (such as Pyright), an error will be thrown when typing enum members.

**Why type function/struct arguments with a specific enum?**
I believe that using specific enums as type arguments can help others who read the code to better understand its intent.

### CODE REVIEW

**Comment by N0I0C0K** [comment]
@unmade PTAL

**Comment by unmade** [comment]
Hey @N0I0C0K 

I really appreciate the effort, thank you for preparing a PR! 

I agree that we don't type annotation on enum members. However to get PR merged the pipeline must be all green. Can you please take a look and fix lint errors and tests? 

Feel free to reach out with any questions you have!

**Comment by N0I0C0K** [comment]
Hi @unmade
I just fixed the part of the test that failed, Then I ran the action again on my own branch. Could you approve again for this pr?

**Comment by N0I0C0K** [comment]
> {"message":"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 668s."}

Looks like there's a problem with the upload coverage report 😶‍🌫️

**Review by unmade — APPROVED** [review]

**Comment by unmade** [comment]
Looks good and thank you for fixing that issue. 
I'm going to release it under a new major version because it introduces a breaking change for existing users.

**Pull request merged**
